---
title: "Consulting"
output:
  html_document:
    toc: false
    #toc_float: true
    #collapsed: false
    #number_sections: false
    #toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


------------------------

### Experience

- **Consultant** (Sept 2019 - June 2020)   
   Location: [GradQuant](https://gradquant.ucr.edu/), University of California Riverside - Riverside, CA   
   <span class="desc">Responsible for holding quantitative consultations, and developing and presenting workshops for a variety of topics and programs. Assisted with the creation of resources and promotion of GradQuant through social media and on-campus events. Specialized In: LaTeX, Python, R, Matlab, Machine learning, Probability theory, Statistical computing, Statistical inference, Web scraping, Advanced Statistical Methods. </span>
   
- **Graduate Student Researcher - Intern** (Oct 2020 - Sept 2021)      
  Location: Mathematical Analysis Research Corps - Claremont, CA   
   <span class="desc">Consult on unique statistical and computational problems where solutions may result in publication. Work on long term projects both as a team and at an individual level. Interact with others that have a variety of different backgrounds, responsible for handling sensitive information. Prepare and present materials for a specialized audience</span>

### Workshops 

The majority of workshops were prepared and presented by myself. These workshops were created for a variety of audiences, including high school, undergraduate and graduate students, faculty research groups, and professional groups. Many of these workshops were implemented multiple times, with modifications for the specific setting and audience. Some of these workshops were implemented as part of my positions above, but I have not listed any workshops/tutorials that are a part of courses I have taught or taken. Some of my workshop materials are readily available on my github account.  If there is one you would like but it is not there please send me an email.  In no particular order: 

**Coding Based Workshops**

- An Introduction to the R Programming Language 
- Random Forests in R 
- A Comparison of Iteration Methods in R 
- Debugging Techniques in R
- Building Your First Shiny App in R
- A Crash Course in Python for R Users 
- Advanced Text Analysis in R
- R-documents (Markdown, Powerpoints, Dashboards, Websites, etc.) 


**Statistical Theory Based Workshops** 

- Hypothesis Testing
- Causal Inference 
- How to Handle Missing Data 
- Nonparametric Testing Procedures 
- Decision Trees
- Fisher's Exact Test and Alternative Testing Procedures